//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("corrales_eventosModel", "FK_CLIENTE", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExpandCollapsePanelDemo.Entidades.cliente), "reservacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpandCollapsePanelDemo.Entidades.reservacion), true)]
[assembly: EdmRelationshipAttribute("corrales_eventosModel", "FK_PAQUETE", "paquete", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExpandCollapsePanelDemo.Entidades.paquete), "reservacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpandCollapsePanelDemo.Entidades.reservacion), true)]
[assembly: EdmRelationshipAttribute("corrales_eventosModel", "FK_IDRESERVACION", "reservacion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExpandCollapsePanelDemo.Entidades.reservacion), "seguimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpandCollapsePanelDemo.Entidades.seguimiento), true)]

#endregion

namespace ExpandCollapsePanelDemo.Entidades
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class corrales_eventosEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto corrales_eventosEntities usando la cadena de conexión encontrada en la sección 'corrales_eventosEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public corrales_eventosEntities() : base("name=corrales_eventosEntities", "corrales_eventosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto corrales_eventosEntities.
        /// </summary>
        public corrales_eventosEntities(string connectionString) : base(connectionString, "corrales_eventosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto corrales_eventosEntities.
        /// </summary>
        public corrales_eventosEntities(EntityConnection connection) : base(connection, "corrales_eventosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cliente> cliente
        {
            get
            {
                if ((_cliente == null))
                {
                    _cliente = base.CreateObjectSet<cliente>("cliente");
                }
                return _cliente;
            }
        }
        private ObjectSet<cliente> _cliente;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<paquete> paquete
        {
            get
            {
                if ((_paquete == null))
                {
                    _paquete = base.CreateObjectSet<paquete>("paquete");
                }
                return _paquete;
            }
        }
        private ObjectSet<paquete> _paquete;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<permisos> permisos
        {
            get
            {
                if ((_permisos == null))
                {
                    _permisos = base.CreateObjectSet<permisos>("permisos");
                }
                return _permisos;
            }
        }
        private ObjectSet<permisos> _permisos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<seguimiento> seguimiento
        {
            get
            {
                if ((_seguimiento == null))
                {
                    _seguimiento = base.CreateObjectSet<seguimiento>("seguimiento");
                }
                return _seguimiento;
            }
        }
        private ObjectSet<seguimiento> _seguimiento;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tipo_evento> tipo_evento
        {
            get
            {
                if ((_tipo_evento == null))
                {
                    _tipo_evento = base.CreateObjectSet<tipo_evento>("tipo_evento");
                }
                return _tipo_evento;
            }
        }
        private ObjectSet<tipo_evento> _tipo_evento;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<catalogos> catalogos
        {
            get
            {
                if ((_catalogos == null))
                {
                    _catalogos = base.CreateObjectSet<catalogos>("catalogos");
                }
                return _catalogos;
            }
        }
        private ObjectSet<catalogos> _catalogos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<reservacion> reservacion
        {
            get
            {
                if ((_reservacion == null))
                {
                    _reservacion = base.CreateObjectSet<reservacion>("reservacion");
                }
                return _reservacion;
            }
        }
        private ObjectSet<reservacion> _reservacion;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet cliente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocliente(cliente cliente)
        {
            base.AddObject("cliente", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet paquete. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopaquete(paquete paquete)
        {
            base.AddObject("paquete", paquete);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet permisos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopermisos(permisos permisos)
        {
            base.AddObject("permisos", permisos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet seguimiento. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToseguimiento(seguimiento seguimiento)
        {
            base.AddObject("seguimiento", seguimiento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tipo_evento. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotipo_evento(tipo_evento tipo_evento)
        {
            base.AddObject("tipo_evento", tipo_evento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet catalogos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocatalogos(catalogos catalogos)
        {
            base.AddObject("catalogos", catalogos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet reservacion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToreservacion(reservacion reservacion)
        {
            base.AddObject("reservacion", reservacion);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_eventosModel", Name="catalogos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class catalogos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto catalogos.
        /// </summary>
        /// <param name="idcatalogo">Valor inicial de la propiedad idcatalogo.</param>
        public static catalogos Createcatalogos(global::System.Int32 idcatalogo)
        {
            catalogos catalogos = new catalogos();
            catalogos.idcatalogo = idcatalogo;
            return catalogos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcatalogo
        {
            get
            {
                return _idcatalogo;
            }
            set
            {
                if (_idcatalogo != value)
                {
                    OnidcatalogoChanging(value);
                    ReportPropertyChanging("idcatalogo");
                    _idcatalogo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcatalogo");
                    OnidcatalogoChanged();
                }
            }
        }
        private global::System.Int32 _idcatalogo;
        partial void OnidcatalogoChanging(global::System.Int32 value);
        partial void OnidcatalogoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre_tabla
        {
            get
            {
                return _nombre_tabla;
            }
            set
            {
                Onnombre_tablaChanging(value);
                ReportPropertyChanging("nombre_tabla");
                _nombre_tabla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre_tabla");
                Onnombre_tablaChanged();
            }
        }
        private global::System.String _nombre_tabla;
        partial void Onnombre_tablaChanging(global::System.String value);
        partial void Onnombre_tablaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_eventosModel", Name="cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cliente.
        /// </summary>
        /// <param name="idcliente">Valor inicial de la propiedad idcliente.</param>
        public static cliente Createcliente(global::System.Int32 idcliente)
        {
            cliente cliente = new cliente();
            cliente.idcliente = idcliente;
            return cliente;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcliente
        {
            get
            {
                return _idcliente;
            }
            set
            {
                if (_idcliente != value)
                {
                    OnidclienteChanging(value);
                    ReportPropertyChanging("idcliente");
                    _idcliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcliente");
                    OnidclienteChanged();
                }
            }
        }
        private global::System.Int32 _idcliente;
        partial void OnidclienteChanging(global::System.Int32 value);
        partial void OnidclienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_eventosModel", "FK_CLIENTE", "reservacion")]
        public EntityCollection<reservacion> reservacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<reservacion>("corrales_eventosModel.FK_CLIENTE", "reservacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<reservacion>("corrales_eventosModel.FK_CLIENTE", "reservacion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_eventosModel", Name="paquete")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paquete : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto paquete.
        /// </summary>
        /// <param name="idpaquete">Valor inicial de la propiedad idpaquete.</param>
        /// <param name="costo">Valor inicial de la propiedad costo.</param>
        public static paquete Createpaquete(global::System.Int32 idpaquete, global::System.Double costo)
        {
            paquete paquete = new paquete();
            paquete.idpaquete = idpaquete;
            paquete.costo = costo;
            return paquete;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idpaquete
        {
            get
            {
                return _idpaquete;
            }
            set
            {
                if (_idpaquete != value)
                {
                    OnidpaqueteChanging(value);
                    ReportPropertyChanging("idpaquete");
                    _idpaquete = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idpaquete");
                    OnidpaqueteChanged();
                }
            }
        }
        private global::System.Int32 _idpaquete;
        partial void OnidpaqueteChanging(global::System.Int32 value);
        partial void OnidpaqueteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double costo
        {
            get
            {
                return _costo;
            }
            set
            {
                OncostoChanging(value);
                ReportPropertyChanging("costo");
                _costo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("costo");
                OncostoChanged();
            }
        }
        private global::System.Double _costo;
        partial void OncostoChanging(global::System.Double value);
        partial void OncostoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_eventosModel", "FK_PAQUETE", "reservacion")]
        public EntityCollection<reservacion> reservacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<reservacion>("corrales_eventosModel.FK_PAQUETE", "reservacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<reservacion>("corrales_eventosModel.FK_PAQUETE", "reservacion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_eventosModel", Name="permisos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class permisos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto permisos.
        /// </summary>
        /// <param name="idpermiso">Valor inicial de la propiedad idpermiso.</param>
        public static permisos Createpermisos(global::System.Int32 idpermiso)
        {
            permisos permisos = new permisos();
            permisos.idpermiso = idpermiso;
            return permisos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idpermiso
        {
            get
            {
                return _idpermiso;
            }
            set
            {
                if (_idpermiso != value)
                {
                    OnidpermisoChanging(value);
                    ReportPropertyChanging("idpermiso");
                    _idpermiso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idpermiso");
                    OnidpermisoChanged();
                }
            }
        }
        private global::System.Int32 _idpermiso;
        partial void OnidpermisoChanging(global::System.Int32 value);
        partial void OnidpermisoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_eventosModel", Name="reservacion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class reservacion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto reservacion.
        /// </summary>
        /// <param name="idreservacion">Valor inicial de la propiedad idreservacion.</param>
        /// <param name="no_reservacion">Valor inicial de la propiedad no_reservacion.</param>
        /// <param name="idcliente">Valor inicial de la propiedad idcliente.</param>
        /// <param name="idpaquete">Valor inicial de la propiedad idpaquete.</param>
        /// <param name="idusuario">Valor inicial de la propiedad idusuario.</param>
        /// <param name="idtevento">Valor inicial de la propiedad idtevento.</param>
        /// <param name="fecha_reservacion">Valor inicial de la propiedad fecha_reservacion.</param>
        /// <param name="hora_reservacion">Valor inicial de la propiedad hora_reservacion.</param>
        /// <param name="total">Valor inicial de la propiedad total.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        /// <param name="saldo">Valor inicial de la propiedad saldo.</param>
        public static reservacion Createreservacion(global::System.Int32 idreservacion, global::System.String no_reservacion, global::System.Int32 idcliente, global::System.Int32 idpaquete, global::System.Int32 idusuario, global::System.Int32 idtevento, global::System.DateTime fecha_reservacion, global::System.TimeSpan hora_reservacion, global::System.Double total, global::System.String estatus, global::System.Double saldo)
        {
            reservacion reservacion = new reservacion();
            reservacion.idreservacion = idreservacion;
            reservacion.no_reservacion = no_reservacion;
            reservacion.idcliente = idcliente;
            reservacion.idpaquete = idpaquete;
            reservacion.idusuario = idusuario;
            reservacion.idtevento = idtevento;
            reservacion.fecha_reservacion = fecha_reservacion;
            reservacion.hora_reservacion = hora_reservacion;
            reservacion.total = total;
            reservacion.estatus = estatus;
            reservacion.saldo = saldo;
            return reservacion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idreservacion
        {
            get
            {
                return _idreservacion;
            }
            set
            {
                if (_idreservacion != value)
                {
                    OnidreservacionChanging(value);
                    ReportPropertyChanging("idreservacion");
                    _idreservacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idreservacion");
                    OnidreservacionChanged();
                }
            }
        }
        private global::System.Int32 _idreservacion;
        partial void OnidreservacionChanging(global::System.Int32 value);
        partial void OnidreservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String no_reservacion
        {
            get
            {
                return _no_reservacion;
            }
            set
            {
                Onno_reservacionChanging(value);
                ReportPropertyChanging("no_reservacion");
                _no_reservacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("no_reservacion");
                Onno_reservacionChanged();
            }
        }
        private global::System.String _no_reservacion;
        partial void Onno_reservacionChanging(global::System.String value);
        partial void Onno_reservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcliente
        {
            get
            {
                return _idcliente;
            }
            set
            {
                OnidclienteChanging(value);
                ReportPropertyChanging("idcliente");
                _idcliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idcliente");
                OnidclienteChanged();
            }
        }
        private global::System.Int32 _idcliente;
        partial void OnidclienteChanging(global::System.Int32 value);
        partial void OnidclienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idpaquete
        {
            get
            {
                return _idpaquete;
            }
            set
            {
                OnidpaqueteChanging(value);
                ReportPropertyChanging("idpaquete");
                _idpaquete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idpaquete");
                OnidpaqueteChanged();
            }
        }
        private global::System.Int32 _idpaquete;
        partial void OnidpaqueteChanging(global::System.Int32 value);
        partial void OnidpaqueteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                OnidusuarioChanging(value);
                ReportPropertyChanging("idusuario");
                _idusuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idusuario");
                OnidusuarioChanged();
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idtevento
        {
            get
            {
                return _idtevento;
            }
            set
            {
                OnidteventoChanging(value);
                ReportPropertyChanging("idtevento");
                _idtevento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idtevento");
                OnidteventoChanged();
            }
        }
        private global::System.Int32 _idtevento;
        partial void OnidteventoChanging(global::System.Int32 value);
        partial void OnidteventoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_reservacion
        {
            get
            {
                return _fecha_reservacion;
            }
            set
            {
                Onfecha_reservacionChanging(value);
                ReportPropertyChanging("fecha_reservacion");
                _fecha_reservacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_reservacion");
                Onfecha_reservacionChanged();
            }
        }
        private global::System.DateTime _fecha_reservacion;
        partial void Onfecha_reservacionChanging(global::System.DateTime value);
        partial void Onfecha_reservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan hora_reservacion
        {
            get
            {
                return _hora_reservacion;
            }
            set
            {
                Onhora_reservacionChanging(value);
                ReportPropertyChanging("hora_reservacion");
                _hora_reservacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hora_reservacion");
                Onhora_reservacionChanged();
            }
        }
        private global::System.TimeSpan _hora_reservacion;
        partial void Onhora_reservacionChanging(global::System.TimeSpan value);
        partial void Onhora_reservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private global::System.Double _total;
        partial void OntotalChanging(global::System.Double value);
        partial void OntotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double saldo
        {
            get
            {
                return _saldo;
            }
            set
            {
                OnsaldoChanging(value);
                ReportPropertyChanging("saldo");
                _saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldo");
                OnsaldoChanged();
            }
        }
        private global::System.Double _saldo;
        partial void OnsaldoChanging(global::System.Double value);
        partial void OnsaldoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_eventosModel", "FK_CLIENTE", "cliente")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("corrales_eventosModel.FK_CLIENTE", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("corrales_eventosModel.FK_CLIENTE", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("corrales_eventosModel.FK_CLIENTE", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("corrales_eventosModel.FK_CLIENTE", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_eventosModel", "FK_PAQUETE", "paquete")]
        public paquete paquete
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paquete>("corrales_eventosModel.FK_PAQUETE", "paquete").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paquete>("corrales_eventosModel.FK_PAQUETE", "paquete").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<paquete> paqueteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paquete>("corrales_eventosModel.FK_PAQUETE", "paquete");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<paquete>("corrales_eventosModel.FK_PAQUETE", "paquete", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_eventosModel", "FK_IDRESERVACION", "seguimiento")]
        public EntityCollection<seguimiento> seguimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<seguimiento>("corrales_eventosModel.FK_IDRESERVACION", "seguimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<seguimiento>("corrales_eventosModel.FK_IDRESERVACION", "seguimiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_eventosModel", Name="seguimiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class seguimiento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto seguimiento.
        /// </summary>
        /// <param name="idseguimiento">Valor inicial de la propiedad idseguimiento.</param>
        /// <param name="idreservacion">Valor inicial de la propiedad idreservacion.</param>
        /// <param name="fecha_seguimiento">Valor inicial de la propiedad fecha_seguimiento.</param>
        public static seguimiento Createseguimiento(global::System.Int32 idseguimiento, global::System.Int32 idreservacion, global::System.DateTime fecha_seguimiento)
        {
            seguimiento seguimiento = new seguimiento();
            seguimiento.idseguimiento = idseguimiento;
            seguimiento.idreservacion = idreservacion;
            seguimiento.fecha_seguimiento = fecha_seguimiento;
            return seguimiento;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idseguimiento
        {
            get
            {
                return _idseguimiento;
            }
            set
            {
                if (_idseguimiento != value)
                {
                    OnidseguimientoChanging(value);
                    ReportPropertyChanging("idseguimiento");
                    _idseguimiento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idseguimiento");
                    OnidseguimientoChanged();
                }
            }
        }
        private global::System.Int32 _idseguimiento;
        partial void OnidseguimientoChanging(global::System.Int32 value);
        partial void OnidseguimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idreservacion
        {
            get
            {
                return _idreservacion;
            }
            set
            {
                OnidreservacionChanging(value);
                ReportPropertyChanging("idreservacion");
                _idreservacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idreservacion");
                OnidreservacionChanged();
            }
        }
        private global::System.Int32 _idreservacion;
        partial void OnidreservacionChanging(global::System.Int32 value);
        partial void OnidreservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_seguimiento
        {
            get
            {
                return _fecha_seguimiento;
            }
            set
            {
                Onfecha_seguimientoChanging(value);
                ReportPropertyChanging("fecha_seguimiento");
                _fecha_seguimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_seguimiento");
                Onfecha_seguimientoChanged();
            }
        }
        private global::System.DateTime _fecha_seguimiento;
        partial void Onfecha_seguimientoChanging(global::System.DateTime value);
        partial void Onfecha_seguimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String observacion
        {
            get
            {
                return _observacion;
            }
            set
            {
                OnobservacionChanging(value);
                ReportPropertyChanging("observacion");
                _observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("observacion");
                OnobservacionChanged();
            }
        }
        private global::System.String _observacion;
        partial void OnobservacionChanging(global::System.String value);
        partial void OnobservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> deposito
        {
            get
            {
                return _deposito;
            }
            set
            {
                OndepositoChanging(value);
                ReportPropertyChanging("deposito");
                _deposito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deposito");
                OndepositoChanged();
            }
        }
        private Nullable<global::System.Double> _deposito;
        partial void OndepositoChanging(Nullable<global::System.Double> value);
        partial void OndepositoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> saldo
        {
            get
            {
                return _saldo;
            }
            set
            {
                OnsaldoChanging(value);
                ReportPropertyChanging("saldo");
                _saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldo");
                OnsaldoChanged();
            }
        }
        private Nullable<global::System.Double> _saldo;
        partial void OnsaldoChanging(Nullable<global::System.Double> value);
        partial void OnsaldoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("corrales_eventosModel", "FK_IDRESERVACION", "reservacion")]
        public reservacion reservacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<reservacion>("corrales_eventosModel.FK_IDRESERVACION", "reservacion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<reservacion>("corrales_eventosModel.FK_IDRESERVACION", "reservacion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<reservacion> reservacionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<reservacion>("corrales_eventosModel.FK_IDRESERVACION", "reservacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<reservacion>("corrales_eventosModel.FK_IDRESERVACION", "reservacion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_eventosModel", Name="tipo_evento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipo_evento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tipo_evento.
        /// </summary>
        /// <param name="idtevento">Valor inicial de la propiedad idtevento.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="status">Valor inicial de la propiedad status.</param>
        public static tipo_evento Createtipo_evento(global::System.Int32 idtevento, global::System.String nombre, global::System.String status)
        {
            tipo_evento tipo_evento = new tipo_evento();
            tipo_evento.idtevento = idtevento;
            tipo_evento.nombre = nombre;
            tipo_evento.status = status;
            return tipo_evento;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idtevento
        {
            get
            {
                return _idtevento;
            }
            set
            {
                if (_idtevento != value)
                {
                    OnidteventoChanging(value);
                    ReportPropertyChanging("idtevento");
                    _idtevento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idtevento");
                    OnidteventoChanged();
                }
            }
        }
        private global::System.Int32 _idtevento;
        partial void OnidteventoChanging(global::System.Int32 value);
        partial void OnidteventoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="corrales_eventosModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="idusuario">Valor inicial de la propiedad idusuario.</param>
        public static usuarios Createusuarios(global::System.Int32 idusuario)
        {
            usuarios usuarios = new usuarios();
            usuarios.idusuario = idusuario;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();

        #endregion

    
    }

    #endregion

    
}
